/* 
 * File:   Constants.h
 * Author: frox
 *
 * Created on May 22, 2014, 2:42 PM
 */

#ifndef CONSTANTS_H
#define	CONSTANTS_H
#include <iostream>

#define CARDS_CNT   13
#define SUITS_CNT   4

enum SUITS{HEARTS=0,DIAMONDS=1,CLUBS=2,SPADES=3};
enum CARDS{CARD_2,CARD_3,CARD_4,CARD_5,CARD_6,CARD_7,CARD_8,CARD_9,CARD_10,JACK,QUEEN,KING,ACE};
#define RANK_GAP 1000000    
enum FIGURE_RANK {HIGH_CARD = 10,ONE_PAIR=3*RANK_GAP,TWO_PAIRS=4*RANK_GAP,THREE=5*RANK_GAP,FLUSH=6*RANK_GAP,FULL_HOUSE=7*RANK_GAP,POKER=8*RANK_GAP,STRAIGHT_FLUSH=9*RANK_GAP};

#endif	/* CONSTANTS_H */

