/* 
 * File:   Constants.h
 * Author: frox
 *
 * Created on May 22, 2014, 2:42 PM
 */

#ifndef CONSTANTS_H
#define	CONSTANTS_H
#include <iostream>

#define CARDS_CNT   14
#define SUITS_CNT   4

enum SUITS {
    HEARTS = 0, DIAMONDS = 1, CLUBS = 2, SPADES = 3
};

enum CARDS {
    NO_CARD, CARD_2, CARD_3, CARD_4, CARD_5, CARD_6, CARD_7, CARD_8, CARD_9, CARD_10, JACK, QUEEN, KING, ACE
};
#define RANK_GAP 100000000
#define SIGNIFICANCE_BITS (4 * 5)
#define FIGURE_RANK_MULTIPLIER 1000000

enum FIGURE_RANK {
    HIGH_CARD = 0, ONE_PAIR = 1 << SIGNIFICANCE_BITS, TWO_PAIRS = 2 << SIGNIFICANCE_BITS, THREE = 3 << SIGNIFICANCE_BITS, STRAIGHT = 4 << SIGNIFICANCE_BITS, FLUSH = 5 << SIGNIFICANCE_BITS, FULL_HOUSE = 6 << SIGNIFICANCE_BITS, POKER = 7 << SIGNIFICANCE_BITS, STRAIGHT_FLUSH = 8 << SIGNIFICANCE_BITS
};

#endif	/* CONSTANTS_H */

